// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxI1-AXjOcL-ch970ym_9eynxB1Q2VEo',
    appId: '1:747212084608:web:7924793b3d9f671b8e9d65',
    messagingSenderId: '747212084608',
    projectId: 'serenemind-dd752',
    authDomain: 'serenemind-dd752.firebaseapp.com',
    storageBucket: 'serenemind-dd752.appspot.com',
    measurementId: 'G-LYWZSGN9CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjILfRiiLhBC6WVgeLiFAsSBm7mMYTaW0',
    appId: '1:747212084608:android:4aee30e44949404f8e9d65',
    messagingSenderId: '747212084608',
    projectId: 'serenemind-dd752',
    storageBucket: 'serenemind-dd752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTo-NpxPgy4FWHRE3Yo2XBkkbfDj09XY',
    appId: '1:747212084608:ios:8af7985da17c96a68e9d65',
    messagingSenderId: '747212084608',
    projectId: 'serenemind-dd752',
    storageBucket: 'serenemind-dd752.appspot.com',
    iosBundleId: 'com.example.serenemind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTo-NpxPgy4FWHRE3Yo2XBkkbfDj09XY',
    appId: '1:747212084608:ios:8af7985da17c96a68e9d65',
    messagingSenderId: '747212084608',
    projectId: 'serenemind-dd752',
    storageBucket: 'serenemind-dd752.appspot.com',
    iosBundleId: 'com.example.serenemind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDxI1-AXjOcL-ch970ym_9eynxB1Q2VEo',
    appId: '1:747212084608:web:d4bc76f68cbf67048e9d65',
    messagingSenderId: '747212084608',
    projectId: 'serenemind-dd752',
    authDomain: 'serenemind-dd752.firebaseapp.com',
    storageBucket: 'serenemind-dd752.appspot.com',
    measurementId: 'G-XCNVY3TH3K',
  );

}